network:
  ethernets:
    eth0:      
      dhcp4: true      
      match:
        macaddress: 08:00:27:99:ea:33
      nameservers:
        addresses:
        - 8.8.8.8
        - 8.8.4.4
      set-name: eth0
    eth1:
      addresses:
      - 192.168.2.1/24
      match:
        macaddress: 08:00:27:ce:9f:19
      set-name: eth1
    eth2:
      addresses:
      - 192.168.3.1/24
      dhcp4: false
      match:
        macaddress: 08:01:00:00:00:00
      nameservers:
        addresses:
        - 8.8.8.8
        - 8.8.4.4
      set-name: eth2
  version: 2
